# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 700)
        Form.setStyleSheet("background-color: rgb(148, 143, 124);")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(42, 469, 278, 45))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(15, 86, 90);\n"
"border-radius: 10px;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 540, 278, 45))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(15, 86, 90);\n"
"border-radius: 10px;")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 18, 221, 47))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(15, 86, 90);\n"
"border-radius: 10px;")
        self.label.setObjectName("label")
        self.total_text = QtWidgets.QLineEdit(Form)
        self.total_text.setGeometry(QtCore.QRect(380, 537, 274, 45))
        self.total_text.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.total_text.setObjectName("total_text")
        self.total_text.setReadOnly(True)
        self.seance_list = QtWidgets.QListWidget(Form)
        self.seance_list.setGeometry(QtCore.QRect(371, 77, 296, 372))
        self.seance_list.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-radius: 10px;")
        self.seance_list.setObjectName("seance_list")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(408, 18, 221, 47))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(15, 86, 90);\n"
"border-radius: 10px;")
        self.label_2.setObjectName("label_2")
        self.all_history = QtWidgets.QPushButton(Form)
        self.all_history.setGeometry(QtCore.QRect(408, 609, 221, 55))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.all_history.setFont(font)
        self.all_history.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(23, 137, 143);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(14, 85, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"border-radius: 20px\n"
"}\n"
"")
        self.all_history.setObjectName("all_history")
        self.movie_list = QtWidgets.QListWidget(Form)
        self.movie_list.setGeometry(QtCore.QRect(33, 77, 296, 372))
        self.movie_list.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-radius: 10px;")
        self.movie_list.setObjectName("movie_list")
        self.add_movie = QtWidgets.QPushButton(Form)
        self.add_movie.setGeometry(QtCore.QRect(70, 609, 221, 55))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.add_movie.setFont(font)
        self.add_movie.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(23, 137, 143);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(14, 85, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"border-radius: 20px\n"
"}\n"
"")
        self.add_movie.setObjectName("add_movie")
        self.totalofmovie_text = QtWidgets.QLineEdit(Form)
        self.totalofmovie_text.setReadOnly(true)
        self.totalofmovie_text.setGeometry(QtCore.QRect(380, 469, 274, 45))
        self.totalofmovie_text.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.totalofmovie_text.setObjectName("totalofmovie_text")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "main (Admin)"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ffffff;\">Total of Movie</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ffffff;\">Total</span></p></body></html>"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ffffff;\">Movies</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ffffff;\">Seance</span></p></body></html>"))
        self.all_history.setText(_translate("Form", "All History"))
        self.add_movie.setText(_translate("Form", "Add Movie"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
