# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_Window(object):
    def setupUi(self, Login_Window):
        Login_Window.setObjectName("Login_Window")
        Login_Window.resize(300, 400)
        Login_Window.setStyleSheet("background-color:rgb(148, 143, 124)")
        self.label = QtWidgets.QLabel(Login_Window)
        self.label.setGeometry(QtCore.QRect(60, 10, 191, 31))
        self.label.setStyleSheet("background-color:rgb(15, 86, 90)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Login_Window)
        self.label_2.setGeometry(QtCore.QRect(60, 110, 191, 31))
        self.label_2.setStyleSheet("background-color:rgb(15, 86, 90)")
        self.label_2.setObjectName("label_2")
        self.username = QtWidgets.QLineEdit(Login_Window)
        self.username.setGeometry(QtCore.QRect(60, 50, 191, 31))
        self.username.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(Login_Window)
        self.password.setGeometry(QtCore.QRect(60, 150, 191, 31))
        self.password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.pushButton = QtWidgets.QPushButton(Login_Window)
        self.pushButton.setGeometry(QtCore.QRect(80, 250, 161, 61))
        self.pushButton.setStyleSheet("background-color: rgb(15, 86, 90);\n"
"font-size: 30px;\n"
"color: white")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Login_Window)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 330, 141, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(15, 86, 90);\n"
"font-size: 25px;\n"
"color: white")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Login_Window)
        QtCore.QMetaObject.connectSlotsByName(Login_Window)

    def retranslateUi(self, Login_Window):
        _translate = QtCore.QCoreApplication.translate
        Login_Window.setWindowTitle(_translate("Login_Window", "Dialog"))
        self.label.setText(_translate("Login_Window", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ffffff;\">Username</span></p></body></html>"))
        self.label_2.setText(_translate("Login_Window", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ffffff;\">Password</span></p></body></html>"))
        self.pushButton.setText(_translate("Login_Window", "LogIn"))
        self.pushButton_2.setText(_translate("Login_Window", "Registration"))
