# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main_wind(object):
    def setupUi(self, Main_wind):
        Main_wind.setObjectName("Main_wind")
        Main_wind.resize(700, 700)
        Main_wind.setStyleSheet("background-color: rgb(148, 143, 124);")
        self.label_2 = QtWidgets.QLabel(Main_wind)
        self.label_2.setGeometry(QtCore.QRect(380, 40, 251, 41))
        self.label_2.setStyleSheet("background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"border-radius: 20px")
        self.label_2.setObjectName("label_2")
        self.history = QtWidgets.QPushButton(Main_wind)
        self.history.setGeometry(QtCore.QRect(489, 530, 141, 51))
        self.history.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(23, 137, 143);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(14, 85, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"border-radius: 20px\n"
"}\n"
"")
        self.history.setObjectName("history")
        self.movies_table = QtWidgets.QTableView(Main_wind)
        self.movies_table.setGeometry(QtCore.QRect(90, 100, 256, 371))
        self.movies_table.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.movies_table.setObjectName("movies_table")
        self.info = QtWidgets.QPushButton(Main_wind)
        self.info.setGeometry(QtCore.QRect(100, 530, 130, 51))
        self.info.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(23, 137, 143);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(14, 85, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"border-radius: 20px\n"
"}\n"
"")
        self.info.setObjectName("info")
        self.buy_tickets = QtWidgets.QPushButton(Main_wind)
        self.buy_tickets.setGeometry(QtCore.QRect(300, 530, 130, 51))
        self.buy_tickets.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(23, 137, 143);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(14, 85, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"border-radius: 20px\n"
"}\n"
"")
        self.buy_tickets.setObjectName("buy_tickets")
        self.label = QtWidgets.QLabel(Main_wind)
        self.label.setGeometry(QtCore.QRect(90, 40, 251, 41))
        self.label.setStyleSheet("background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"border-radius: 20px")
        self.label.setObjectName("label")
        self.seance_table = QtWidgets.QTableView(Main_wind)
        self.seance_table.setGeometry(QtCore.QRect(380, 100, 261, 371))
        self.seance_table.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.seance_table.setObjectName("seance_table")
        self.exit_button = QtWidgets.QPushButton(Main_wind)
        self.exit_button.setGeometry(QtCore.QRect(0, 660, 121, 41))
        self.exit_button.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(23, 137, 143);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(14, 85, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 20px;\n"
"border-radius: 20px\n"
"}\n"
"")
        self.exit_button.setObjectName("exit_button")

        self.retranslateUi(Main_wind)
        QtCore.QMetaObject.connectSlotsByName(Main_wind)

    def retranslateUi(self, Main_wind):
        _translate = QtCore.QCoreApplication.translate
        Main_wind.setWindowTitle(_translate("Main_wind", "Form"))
        self.label_2.setText(_translate("Main_wind", "<html><head/><body><p align=\"center\">Seance</p></body></html>"))
        self.history.setText(_translate("Main_wind", "HISTORY"))
        self.info.setText(_translate("Main_wind", "INFO"))
        self.buy_tickets.setText(_translate("Main_wind", "BUY"))
        self.label.setText(_translate("Main_wind", "<html><head/><body><p align=\"center\">Movies</p></body></html>"))
        self.exit_button.setText(_translate("Main_wind", "EXIT"))
