# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main_wind(QtWidgets.QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 550)
        Form.setStyleSheet("background-color: rgb(148, 143, 124);")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(340, 20, 251, 41))
        self.label_2.setStyleSheet("background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"border-radius: 20px")
        self.label_2.setObjectName("label_2")
        self.history = QtWidgets.QPushButton(Form)
        self.history.setGeometry(QtCore.QRect(449, 470, 141, 51))
        self.history.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(23, 137, 143);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(14, 85, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"border-radius: 20px\n"
"}\n"
"")
        self.history.setObjectName("history")
        self.info = QtWidgets.QPushButton(Form)
        self.info.setGeometry(QtCore.QRect(60, 470, 130, 51))
        self.info.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(23, 137, 143);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(14, 85, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"border-radius: 20px\n"
"}\n"
"")
        self.info.setObjectName("info")
        self.buy_tickets = QtWidgets.QPushButton(Form)
        self.buy_tickets.setGeometry(QtCore.QRect(260, 470, 130, 51))
        self.buy_tickets.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(23, 137, 143);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(14, 85, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"border-radius: 20px\n"
"}\n"
"")
        self.buy_tickets.setObjectName("buy_tickets")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 20, 251, 41))
        self.label.setStyleSheet("background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"border-radius: 20px")
        self.label.setObjectName("label")
        self.exit_button = QtWidgets.QPushButton(Form)
        self.exit_button.setGeometry(QtCore.QRect(0, 660, 121, 41))
        self.exit_button.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(23, 137, 143);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(14, 85, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 20px;\n"
"border-radius: 20px\n"
"}\n"
"")
        self.exit_button.setObjectName("exit_button")
        self.movies_list = QtWidgets.QTextEdit(Form)
        self.movies_list.setGeometry(QtCore.QRect(40, 80, 260, 370))
        self.movies_list.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15px;")
        self.movies_list.setReadOnly(True)
        self.movies_list.setObjectName("movies_list")
        self.seance_list = QtWidgets.QTextEdit(Form)
        self.seance_list.setGeometry(QtCore.QRect(340, 80, 260, 370))
        self.seance_list.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15px;")
        self.seance_list.setReadOnly(True)
        self.seance_list.setObjectName("seance_list")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">Seance</p></body></html>"))
        self.history.setText(_translate("Form", "HISTORY"))
        self.info.setText(_translate("Form", "INFO"))
        self.buy_tickets.setText(_translate("Form", "BUY"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\">Movies</p></body></html>"))
        self.exit_button.setText(_translate("Form", "EXIT"))
