# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registration(object):
    def setupUi(self, Registration):
        Registration.setObjectName("Registration")
        Registration.setWindowModality(QtCore.Qt.ApplicationModal)
        Registration.resize(300, 400)
        Registration.setStyleSheet("background-color:rgb(148, 143, 124)")
        self.label = QtWidgets.QLabel(Registration)
        self.label.setGeometry(QtCore.QRect(40, 10, 231, 31))
        self.label.setStyleSheet("background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 20px;\n"
"border-radius: 15px")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Registration)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 231, 31))
        self.label_2.setStyleSheet("background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 20px;\n"
"border-radius: 15px")
        self.label_2.setObjectName("label_2")
        self.username = QtWidgets.QLineEdit(Registration)
        self.username.setGeometry(QtCore.QRect(60, 50, 191, 31))
        self.username.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(Registration)
        self.password.setGeometry(QtCore.QRect(60, 140, 191, 31))
        self.password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.confirm_password = QtWidgets.QLineEdit(Registration)
        self.confirm_password.setGeometry(QtCore.QRect(60, 230, 191, 31))
        self.confirm_password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.confirm_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm_password.setObjectName("confirm_password")
        self.label_3 = QtWidgets.QLabel(Registration)
        self.label_3.setGeometry(QtCore.QRect(40, 190, 231, 31))
        self.label_3.setStyleSheet("background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 20px;\n"
"border-radius: 15px")
        self.label_3.setObjectName("label_3")
        self.sign_up = QtWidgets.QPushButton(Registration)
        self.sign_up.setGeometry(QtCore.QRect(40, 280, 231, 71))
        self.sign_up.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(23, 137, 143);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 30px\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(14, 85, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius:30px\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"border-radius: 30px\n"
"}\n"
"")
        self.sign_up.setObjectName("sign_up")

        self.retranslateUi(Registration)
        QtCore.QMetaObject.connectSlotsByName(Registration)

    def retranslateUi(self, Registration):
        _translate = QtCore.QCoreApplication.translate
        Registration.setWindowTitle(_translate("Registration", "Registration"))
        self.label.setText(_translate("Registration", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ffffff;\">Username</span></p></body></html>"))
        self.label_2.setText(_translate("Registration", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ffffff;\">Password</span></p></body></html>"))
        self.label_3.setText(_translate("Registration", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ffffff;\">Confirm Password</span></p></body></html>"))
        self.sign_up.setText(_translate("Registration", "Sign Up"))
