# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registration(object):
    def setupUi(self, Registration):
        Registration.setObjectName("Registration")
        Registration.setWindowModality(QtCore.Qt.ApplicationModal)
        Registration.resize(300, 400)
        Registration.setStyleSheet("background-color:rgb(148, 143, 124)")
        self.label_3 = QtWidgets.QLabel(Registration)
        self.label_3.setGeometry(QtCore.QRect(72, 34, 155, 33))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(15, 86, 90);\n"
"border-radius: 10px;")
        self.label_3.setObjectName("label_3")
        self.apply = QtWidgets.QPushButton(Registration)
        self.apply.setGeometry(QtCore.QRect(73, 342, 155, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.apply.setFont(font)
        self.apply.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(23, 137, 143);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(14, 85, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"border-radius: 20px\n"
"}\n"
"")
        self.apply.setObjectName("apply")
        self.label_4 = QtWidgets.QLabel(Registration)
        self.label_4.setGeometry(QtCore.QRect(72, 132, 155, 33))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(15, 86, 90);\n"
"border-radius: 10px;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Registration)
        self.label_5.setGeometry(QtCore.QRect(72, 237, 155, 33))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(15, 86, 90);\n"
"border-radius: 10px;")
        self.label_5.setObjectName("label_5")
        self.name_text = QtWidgets.QLineEdit(Registration)
        self.name_text.setGeometry(QtCore.QRect(38, 77, 223, 38))
        self.name_text.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.name_text.setObjectName("name_text")
        self.password_text = QtWidgets.QLineEdit(Registration)
        self.password_text.setGeometry(QtCore.QRect(38, 182, 223, 38))
        self.password_text.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.password_text.setObjectName("password_text")
        self.confirm_text = QtWidgets.QLineEdit(Registration)
        self.confirm_text.setGeometry(QtCore.QRect(38, 287, 223, 38))
        self.confirm_text.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.confirm_text.setObjectName("confirm_text")

        self.retranslateUi(Registration)
        QtCore.QMetaObject.connectSlotsByName(Registration)

    def retranslateUi(self, Registration):
        _translate = QtCore.QCoreApplication.translate
        Registration.setWindowTitle(_translate("Registration", "Sign Up"))
        self.label_3.setText(_translate("Registration", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">Name</span></p></body></html>"))
        self.apply.setText(_translate("Registration", "Apply"))
        self.label_4.setText(_translate("Registration", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">Password</span></p></body></html>"))
        self.label_5.setText(_translate("Registration", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">Confirm</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Registration = QtWidgets.QDialog()
    ui = Ui_Registration()
    ui.setupUi(Registration)
    Registration.show()
    sys.exit(app.exec_())
