# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_Window(object):
    def setupUi(self, Login_Window):
        Login_Window.setObjectName("Login_Window")
        Login_Window.resize(300, 400)
        Login_Window.setMaximumSize(QtCore.QSize(300, 400))
        Login_Window.setStyleSheet("background-color:rgb(148, 143, 124)")
        self.label_3 = QtWidgets.QLabel(Login_Window)
        self.label_3.setGeometry(QtCore.QRect(72, 34, 155, 33))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(15, 86, 90);\n"
"border-radius: 10px;")
        self.label_3.setObjectName("label_3")
        self.login = QtWidgets.QPushButton(Login_Window)
        self.login.setGeometry(QtCore.QRect(72, 293, 155, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.login.setFont(font)
        self.login.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(23, 137, 143);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(14, 85, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"border-radius: 20px\n"
"}\n"
"")
        self.login.setObjectName("login")
        self.label_4 = QtWidgets.QLabel(Login_Window)
        self.label_4.setGeometry(QtCore.QRect(72, 132, 155, 33))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(15, 86, 90);\n"
"border-radius: 10px;")
        self.label_4.setObjectName("label_4")
        self.new_user = QtWidgets.QPushButton(Login_Window)
        self.new_user.setGeometry(QtCore.QRect(72, 343, 155, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.new_user.setFont(font)
        self.new_user.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(23, 137, 143);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(14, 85, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"border-radius: 20px\n"
"}\n"
"")
        self.new_user.setObjectName("new_user")
        self.username_text = QtWidgets.QLineEdit(Login_Window)
        self.username_text.setGeometry(QtCore.QRect(38, 77, 223, 38))
        self.username_text.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.username_text.setObjectName("username_text")
        self.password_text = QtWidgets.QLineEdit(Login_Window)
        self.password_text.setGeometry(QtCore.QRect(38, 182, 223, 38))
        self.password_text.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.password_text.setObjectName("password_text")

        self.retranslateUi(Login_Window)
        QtCore.QMetaObject.connectSlotsByName(Login_Window)

    def retranslateUi(self, Login_Window):
        _translate = QtCore.QCoreApplication.translate
        Login_Window.setWindowTitle(_translate("Login_Window", "Sign In"))
        self.label_3.setText(_translate("Login_Window", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">User Name</span></p></body></html>"))
        self.login.setText(_translate("Login_Window", "Login"))
        self.label_4.setText(_translate("Login_Window", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">Password</span></p></body></html>"))
        self.new_user.setText(_translate("Login_Window", "New User"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login_Window = QtWidgets.QDialog()
    ui = Ui_Login_Window()
    ui.setupUi(Login_Window)
    Login_Window.show()
    sys.exit(app.exec_())
