# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main_Window(object):
    def setupUi(self, Main_Window):
        Main_Window.setObjectName("Main_Window")
        Main_Window.resize(700, 731)
        Main_Window.setStyleSheet("background-color: rgb(148, 143, 124);")
        self.history = QtWidgets.QPushButton(Main_Window)
        self.history.setGeometry(QtCore.QRect(449, 470, 141, 51))
        self.history.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(23, 137, 143);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(14, 85, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"border-radius: 20px\n"
"}\n"
"")
        self.history.setObjectName("history")
        self.info = QtWidgets.QPushButton(Main_Window)
        self.info.setGeometry(QtCore.QRect(60, 470, 130, 51))
        self.info.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(23, 137, 143);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(14, 85, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"border-radius: 20px\n"
"}\n"
"")
        self.info.setObjectName("info")
        self.movie_list = QtWidgets.QListWidget(Main_Window)
        self.movie_list.setGeometry(QtCore.QRect(36, 105, 296, 439))
        self.movie_list.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-radius: 10px;")
        self.movie_list.setObjectName("movie_list")
        self.seance_list = QtWidgets.QListWidget(Main_Window)
        self.seance_list.setGeometry(QtCore.QRect(374, 105, 296, 439))
        self.seance_list.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-radius: 10px;")
        self.seance_list.setObjectName("seance_list")
        self.label = QtWidgets.QLabel(Main_Window)
        self.label.setGeometry(QtCore.QRect(73, 35, 221, 47))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(15, 86, 90);\n"
"border-radius: 10px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Main_Window)
        self.label_2.setGeometry(QtCore.QRect(411, 35, 221, 47))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(15, 86, 90);\n"
"border-radius: 10px;")
        self.label_2.setObjectName("label_2")
        self.info_2 = QtWidgets.QPushButton(Main_Window)
        self.info_2.setGeometry(QtCore.QRect(44, 601, 172, 48))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.info_2.setFont(font)
        self.info_2.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(23, 137, 143);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(14, 85, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"border-radius: 20px\n"
"}\n"
"")
        self.info_2.setObjectName("info_2")
        self.buy = QtWidgets.QPushButton(Main_Window)
        self.buy.setGeometry(QtCore.QRect(264, 601, 172, 48))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.buy.setFont(font)
        self.buy.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(23, 137, 143);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(14, 85, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"border-radius: 20px\n"
"}\n"
"")
        self.buy.setObjectName("buy")
        self.history_2 = QtWidgets.QPushButton(Main_Window)
        self.history_2.setGeometry(QtCore.QRect(484, 601, 172, 48))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.history_2.setFont(font)
        self.history_2.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(23, 137, 143);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(14, 85, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 30px;\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"border-radius: 20px\n"
"}\n"
"")
        self.history_2.setObjectName("history_2")
        self.log_out = QtWidgets.QPushButton(Main_Window)
        self.log_out.setGeometry(QtCore.QRect(10, 687, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.log_out.setFont(font)
        self.log_out.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(23, 137, 143);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px;\n"
"    border-radius: 15px\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(14, 85, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px;\n"
"    border-radius: 15px\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(15, 86, 90);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 20px;\n"
"border-radius: 15px\n"
"}\n"
"")
        self.log_out.setObjectName("log_out")

        self.retranslateUi(Main_Window)
        QtCore.QMetaObject.connectSlotsByName(Main_Window)

    def retranslateUi(self, Main_Window):
        _translate = QtCore.QCoreApplication.translate
        Main_Window.setWindowTitle(_translate("Main_Window", "Main Window"))
        self.history.setText(_translate("Main_Window", "HISTORY"))
        self.info.setText(_translate("Main_Window", "INFO"))
        self.label.setText(_translate("Main_Window", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ffffff;\">Movies</span></p></body></html>"))
        self.label_2.setText(_translate("Main_Window", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ffffff;\">Seance</span></p></body></html>"))
        self.info_2.setText(_translate("Main_Window", "Info"))
        self.buy.setText(_translate("Main_Window", "Buy"))
        self.history_2.setText(_translate("Main_Window", "History"))
        self.log_out.setText(_translate("Main_Window", "Log Out"))
